object_map: dict[str, list[tuple[str, str]]] = {
	"class ConfigExplosion": [
		("never_cache", "bool"),
		("explosion_radius", "float"),
		("explosion_sprite", "string"),
		("explosion_sprite_emissive", "bool"),
		("explosion_sprite_additive", "bool"),
		("explosion_sprite_random_rotation", "bool"),
		("explosion_sprite_lifetime", "float"),
		("damage", "float"),
		("damage_critical", "class ConfigDamageCritical"),
		("camera_shake", "float"),
		("particle_effect", "bool"),
		("load_this_entity", "string"),
		("light_enabled", "bool"),
		("light_fade_time", "float"),
		("light_r", "unsigned int"),
		("light_g", "unsigned int"),
		("light_b", "unsigned int"),
		("light_radius_coeff", "float"),
		("hole_enabled", "bool"),
		("destroy_non_platform_solid_enabled", "bool"),
		("electricity_count", "int"),
		("min_radius_for_cracks", "int"),
		("crack_count", "int"),
		("knockback_force", "float"),
		("hole_destroy_liquid", "bool"),
		("hole_destroy_physics_dynamic", "bool"),
		("create_cell_material", "string"),
		("create_cell_probability", "int"),
		("background_lightning_count", "int"),
		("spark_material", "string"),
		("material_sparks_min_hp", "int"),
		("material_sparks_probability", "int"),
		("material_sparks_count_min", "int"),
		("material_sparks_count_max", "int"),
		("material_sparks_enabled", "bool"),
		("material_sparks_real", "bool"),
		("material_sparks_scale_with_hp", "bool"),
		("sparks_enabled", "bool"),
		("sparks_count_min", "int"),
		("sparks_count_max", "int"),
		("sparks_inner_radius_coeff", "float"),
		("stains_enabled", "bool"),
		("stains_radius", "float"),
		("ray_energy", "int"),
		("max_durability_to_destroy", "int"),
		("gore_particle_count", "int"),
		("shake_vegetation", "bool"),
		("damage_mortals", "bool"),
		("physics_throw_enabled", "bool"),
		("physics_explosion_power", "ValueRange"),
		("physics_multiplier_ragdoll_force", "float"),
		("cell_explosion_power", "float"),
		("cell_explosion_radius_min", "float"),
		("cell_explosion_radius_max", "float"),
		("cell_explosion_velocity_min", "float"),
		("cell_explosion_damage_required", "float"),
		("cell_explosion_probability", "float"),
		("cell_explosion_power_ragdoll_coeff", "float"),
		("pixel_sprites_enabled", "bool"),
		("is_digger", "bool"),
		("audio_enabled", "bool"),
		("audio_event_name", "string"),
		("audio_liquid_amount_normalized", "float"),
		("delay", "ValueRangeInt"),
		("explosion_delay_id", "int"),
		("not_scaled_by_gamefx", "bool"),
	],
	"class ConfigDamageCritical": [("chance", "int"), ("damage_multiplier", "float")],
	"class ConfigDamagesByType": [
		("melee", "float"),
		("projectile", "float"),
		("explosion", "float"),
		("electricity", "float"),
		("fire", "float"),
		("drill", "float"),
		("slice", "float"),
		("ice", "float"),
		("healing", "float"),
		("physics_hit", "float"),
		("radioactive", "float"),
		("poison", "float"),
		("overeating", "float"),
		("curse", "float"),
		("holy", "float"),
	],
	"class ConfigGun": [
		("actions_per_round", "int"),
		("shuffle_deck_when_empty", "bool"),
		("reload_time", "int"),
		("deck_capacity", "int"),
	],
	"class ConfigGunActionInfo": [
		("action_id", "string"),
		("action_name", "string"),
		("action_description", "string"),
		("action_sprite_filename", "string"),
		("action_unidentified_sprite_filename", "string"),
		("action_type", "int"),
		("action_spawn_level", "string"),
		("action_spawn_probability", "string"),
		("action_spawn_requires_flag", "string"),
		("action_spawn_manual_unlock", "bool"),
		("action_max_uses", "int"),
		("custom_xml_file", "string"),
		("action_mana_drain", "float"),
		("action_is_dangerous_blast", "bool"),
		("action_draw_many_count", "int"),
		("action_ai_never_uses", "bool"),
		("action_never_unlimited", "bool"),
		("state_shuffled", "bool"),
		("state_cards_drawn", "int"),
		("state_discarded_action", "bool"),
		("state_destroyed_action", "bool"),
		("fire_rate_wait", "int"),
		("speed_multiplier", "float"),
		("child_speed_multiplier", "float"),
		("dampening", "float"),
		("explosion_radius", "float"),
		("spread_degrees", "float"),
		("pattern_degrees", "float"),
		("screenshake", "float"),
		("recoil", "float"),
		("damage_melee_add", "float"),
		("damage_projectile_add", "float"),
		("damage_electricity_add", "float"),
		("damage_fire_add", "float"),
		("damage_explosion_add", "float"),
		("damage_ice_add", "float"),
		("damage_slice_add", "float"),
		("damage_healing_add", "float"),
		("damage_curse_add", "float"),
		("damage_dri,l_add", "float"),
		("damage_null_all", "float"),
		("damage_critical_chance", "int"),
		("damage_critical_multiplier", "float"),
		("explosion_damage_to_materials", "float"),
		("knockback_force", "float"),
		("reload_time", "int"),
		("lightning_count", "int"),
		("material", "string"),
		("material_amount", "int"),
		("trail_material", "string"),
		("trail_material_amount", "int"),
		("bounces", "int"),
		("gravity", "float"),
		("light", "float"),
		("blood_count_multiplier", "float"),
		("gore_particles", "int"),
		("ragdoll_fx", "int"),
		("friendly_fire", "bool"),
		("physics_impulse_coeff", "float"),
		("lifetime_add", "int"),
		("sprite", "string"),
		("extra_entities", "string"),
		("game_effect_entities", "string"),
		("sound_loop_tag", "string"),
		("projectile_file", "string"),
	],
	"ValueRange": [("min", "float"), ("max", "float")],
	"struct ValueRange": [("min", "float"), ("max", "float")],
	"ValueRangeInt": [("min", "int"), ("max", "int")],
	"struct types::iaabb": [
		("min", "class ceng::math::CVector2<int>"),
		("max", "class ceng::math::CVector2<int>"),
	],
	"struct types::aabb": [
		("min", "class ceng::math::CVector2<float>"),
		("max", "class ceng::math::CVector2<float>"),
	],
	"class ceng::CColorFloat": [
		("r", "float"),
		("g", "float"),
		("b", "float"),
		("a", "float"),
	],
	"struct PathFindingJumpParams": [
		("x", "float"),
		("y", "float"),
		("lob", "float"),
	],
}
