object_map: dict[str, list[tuple[str, str]]] = {
	"class ConfigExplosion": [
		("never_cache", "bool"),
		("explosion_radius", "float"),
		("explosion_sprite", "string"),
		("explosion_sprite_emissive", "bool"),
		("explosion_sprite_additive", "bool"),
		("explosion_sprite_random_rotation", "bool"),
		("explosion_sprite_lifetime", "float"),
		("damage", "float"),
		("damage_critical", "ConfigDamageCritical"),
		("camera_shake", "float"),
		("particle_effect", "bool"),
		("load_this_entity", "string"),
		("light_enabled", "bool"),
		("light_fade_time", "float"),
		("light_r", "unsigned int"),
		("light_g", "unsigned int"),
		("light_b", "unsigned int"),
		("light_radius_coeff", "float"),
		("hole_enabled", "bool"),
		("destroy_non_platform_solid_enabled", "bool"),
		("electricity_count", "int"),
		("min_radius_for_cracks", "int"),
		("crack_count", "int"),
		("knockback_force", "float"),
		("hole_destroy_liquid", "bool"),
		("hole_destroy_physics_dynamic", "bool"),
		("create_cell_material", "string"),
		("create_cell_probability", "int"),
		("background_lightning_count", "int"),
		("spark_material", "string"),
		("material_sparks_min_hp", "int"),
		("material_sparks_probability", "int"),
		("material_sparks_count_min", "int"),
		("material_sparks_count_max", "int"),
		("material_sparks_enabled", "bool"),
		("material_sparks_real", "bool"),
		("material_sparks_scale_with_hp", "bool"),
		("sparks_enabled", "bool"),
		("sparks_count_min", "int"),
		("sparks_count_max", "int"),
		("sparks_inner_radius_coeff", "float"),
		("stains_enabled", "bool"),
		("stains_radius", "float"),
		("ray_energy", "int"),
		("max_durability_to_destroy", "int"),
		("gore_particle_count", "int"),
		("shake_vegetation", "bool"),
		("damage_mortals", "bool"),
		("physics_throw_enabled", "bool"),
		("physics_explosion_power", "ValueRange"),
		("physics_multiplier_ragdoll_force", "float"),
		("cell_explosion_power", "float"),
		("cell_explosion_radius_min", "float"),
		("cell_explosion_radius_max", "float"),
		("cell_explosion_velocity_min", "float"),
		("cell_explosion_damage_required", "float"),
		("cell_explosion_probability", "float"),
		("cell_explosion_power_ragdoll_coeff", "float"),
		("pixel_sprites_enabled", "bool"),
		("is_digger", "bool"),
		("audio_enabled", "bool"),
		("audio_event_name", "string"),
		("audio_liquid_amount_normalized", "float"),
		("delay", "ValueRangeInt"),
		("explosion_delay_id", "int"),
		("not_scaled_by_gamefx", "bool"),
	],
	"ConfigDamageCritical": [("chance", "int"), ("damage_multiplier", "float")],
}
